### ISSUE TITLE
English blog posts

### ISSUE THREAD

**Issue by jfilter** [okfde/okfn.de#53] opened 2019-02-24 21:07 UTC
The site looks awesome. Thanks for your work. I just noticed two things:
- The l18n is not done for the blog. Is this on purpose? Maybe a small note on the English version would help to understand why this part is in German.
- And you can't switch languages when you are on the blog.

**Comment by lislis** [comment] 2019-02-25 15:56
Hey @jfilter!
>  The l18n is not done for the blog. Is this on purpose?

Yes, that is by design. Most blog posts are in German and only recently a few were published with an English translation, so we decided to not translate the Blog as we do with the other pages. 

>   And you can't switch languages when you are on the blog.

Argh, this now is a bug resulting from the translation exception written for the blog :/

Maybe I'll go with your suggestion of having a notice on the "EN Blog". Creating an EN blog would remove the need to have the routing exception for blog and solve the previously mentioned bug.

Thanks for opening this, I'll give it some thought :)

**Comment by lislis** [comment] 2019-03-06 13:32
@jfilter I added a route https://okfn.de/en/blog/ which is the same blog as in German but with a notice. Language switch does now work as expected. 
I'm closing the ticket, feel free to re-open if there is something I've missed

**Closed as completed by lislis** 2019-03-06 13:32 UTC
